name: Release MacOS

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: Release should have a tag (v0.0.0)
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rustup
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin
      - name: Build x86_64
        if: false
        run: ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }} cargo build --target=x86_64-apple-darwin --release
      - name: Build aarch64
        run: ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }} cargo build --target=aarch64-apple-darwin --release
      - name: Lipo
        run: mkdir -p target/release ; lipo -create -output target/release/cmdi target/aarch64-apple-darwin/release/cmdi
      - name: Install Packager
        run: cargo install cargo-packager --locked
      - name: Package
        run: cargo packager --release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            target/release/*.dmg
