name: Release MacOS

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: Release should have a tag (v0.0.0)
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build MacOS
    runs-on: macos-latest
    env:
      CARGO_PROFILE_RELEASE_LTO: true
      CARGO_PROFILE_RELEASE_CODEGEN_UNITS: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rustup
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      # - name: Build x86_64
      #   run: ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }} STORAGE_SALT=${{ secrets.STORAGE_SALT }} SUPABASE_PUBLIC_URL=${{ vars.SUPABASE_PUBLIC_URL }} SUPABASE_PUBLIC_ANON_KEY=${{ vars.SUPABASE_PUBLIC_ANON_KEY }} cargo build --target=x86_64-apple-darwin --release

      - name: Build aarch64
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          STORAGE_SALT: ${{ secrets.STORAGE_SALT }}
          SUPABASE_PUBLIC_URL: ${{ vars.SUPABASE_PUBLIC_URL }}
          SUPABASE_PUBLIC_ANON_KEY: ${{ vars.SUPABASE_PUBLIC_ANON_KEY }}
        run: cargo build --target=aarch64-apple-darwin --release

      - name: Lipo
        # run: mkdir -p target/release ; lipo -create -output target/release/cmdi target/x86_64-apple-darwin/release/cmdi target/aarch64-apple-darwin/release/cmdi
        run: mkdir -p target/release ; lipo -create -output target/release/cmdi target/aarch64-apple-darwin/release/cmdi

      - name: Cache Packager
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/cargo-packager
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-packager
          restore-keys: |
            ${{ runner.os }}-cargo-packager

      - name: Install Packager
        run: |
          if ! command -v cargo-packager &> /dev/null; then
            cargo install cargo-packager --locked
          fi

      - name: Package
        run: cargo packager --release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            target/release/*.dmg
